sudo: required
services:
  - docker
addons:
  apt:
    packages:
    - python3
    - python3-requests
before_install:
  - docker build -t tocco-nginx .
  - |
    docker run -d -u 1234:0 --net=host --name nginx -e NGINX_HEADER_Some-Header='some "value"' \
       -e NGINX_ALWAYS_HEADER_Some__Always__Header='some always "value"' \
       -e IP_WHITELIST='10.0.0.3 10.5.8.0/24 22.88.88.1-22.88.88.7' \
       tocco-nginx
  - |
    while ! [[ $(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8081/status-tocco-nginx") = 200 ]]; do
        echo "waiting for Nginx to become ready"
        docker exec -it nginx true || return
        sleep 1;
    done
script:
  - docker exec nginx nginx -t || { docker logs nginx; false; }
  - PYTHONPATH=$PWD python3 -m unittest discover tests
  - ./tests/integration_tests.py
